apiVersion: v2
name: fluentd-10x
description: A Helm chart for Kubernetes for Fluentd forwarders + 10x Observability engine
keywords:
  - 10x
  - log10x
  - logging
  - fluentd
# type: application
version: 0.2.0
appVersion: 0.2.0
icon: https://raw.githubusercontent.com/log-10x/fluent-helm-charts/main/icon.png
home: https://github.com/log-10x/fluent-helm-charts
sources:
  - https://github.com/log-10x/fluent-helm-charts
  - https://github.com/log-10x/docker-images
  - https://github.com/fluent/fluentd/
  - https://github.com/fluent/fluentd-kubernetes-daemonset
maintainers:
  - name: Log10x
    email: engineering@log10x.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Added 10x Observability engine integration to fluentd"
